-include beast.dep
beast.lo: /Users/mrz/Documents/home/php-beast/beast.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/mrz/Documents/home/php-beast $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/mrz/Documents/home/php-beast/beast.c -o beast.lo  -MMD -MF beast.dep -MT beast.lo
-include aes_algo_handler.dep
aes_algo_handler.lo: /Users/mrz/Documents/home/php-beast/aes_algo_handler.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/mrz/Documents/home/php-beast $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/mrz/Documents/home/php-beast/aes_algo_handler.c -o aes_algo_handler.lo  -MMD -MF aes_algo_handler.dep -MT aes_algo_handler.lo
-include des_algo_handler.dep
des_algo_handler.lo: /Users/mrz/Documents/home/php-beast/des_algo_handler.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/mrz/Documents/home/php-beast $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/mrz/Documents/home/php-beast/des_algo_handler.c -o des_algo_handler.lo  -MMD -MF des_algo_handler.dep -MT des_algo_handler.lo
-include base64_algo_handler.dep
base64_algo_handler.lo: /Users/mrz/Documents/home/php-beast/base64_algo_handler.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/mrz/Documents/home/php-beast $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/mrz/Documents/home/php-beast/base64_algo_handler.c -o base64_algo_handler.lo  -MMD -MF base64_algo_handler.dep -MT base64_algo_handler.lo
-include xxtea_algo_handler.dep
xxtea_algo_handler.lo: /Users/mrz/Documents/home/php-beast/xxtea_algo_handler.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/mrz/Documents/home/php-beast $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/mrz/Documents/home/php-beast/xxtea_algo_handler.c -o xxtea_algo_handler.lo  -MMD -MF xxtea_algo_handler.dep -MT xxtea_algo_handler.lo
-include beast_mm.dep
beast_mm.lo: /Users/mrz/Documents/home/php-beast/beast_mm.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/mrz/Documents/home/php-beast $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/mrz/Documents/home/php-beast/beast_mm.c -o beast_mm.lo  -MMD -MF beast_mm.dep -MT beast_mm.lo
-include spinlock.dep
spinlock.lo: /Users/mrz/Documents/home/php-beast/spinlock.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/mrz/Documents/home/php-beast $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/mrz/Documents/home/php-beast/spinlock.c -o spinlock.lo  -MMD -MF spinlock.dep -MT spinlock.lo
-include cache.dep
cache.lo: /Users/mrz/Documents/home/php-beast/cache.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/mrz/Documents/home/php-beast $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/mrz/Documents/home/php-beast/cache.c -o cache.lo  -MMD -MF cache.dep -MT cache.lo
-include beast_log.dep
beast_log.lo: /Users/mrz/Documents/home/php-beast/beast_log.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/mrz/Documents/home/php-beast $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/mrz/Documents/home/php-beast/beast_log.c -o beast_log.lo  -MMD -MF beast_log.dep -MT beast_log.lo
-include global_algo_modules.dep
global_algo_modules.lo: /Users/mrz/Documents/home/php-beast/global_algo_modules.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/mrz/Documents/home/php-beast $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/mrz/Documents/home/php-beast/global_algo_modules.c -o global_algo_modules.lo  -MMD -MF global_algo_modules.dep -MT global_algo_modules.lo
-include header.dep
header.lo: /Users/mrz/Documents/home/php-beast/header.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/mrz/Documents/home/php-beast $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/mrz/Documents/home/php-beast/header.c -o header.lo  -MMD -MF header.dep -MT header.lo
-include networkcards.dep
networkcards.lo: /Users/mrz/Documents/home/php-beast/networkcards.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/mrz/Documents/home/php-beast $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/mrz/Documents/home/php-beast/networkcards.c -o networkcards.lo  -MMD -MF networkcards.dep -MT networkcards.lo
-include xxtea.dep
xxtea.lo: /Users/mrz/Documents/home/php-beast/xxtea.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/mrz/Documents/home/php-beast $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/mrz/Documents/home/php-beast/xxtea.c -o xxtea.lo  -MMD -MF xxtea.dep -MT xxtea.lo
-include tmpfile_file_handler.dep
tmpfile_file_handler.lo: /Users/mrz/Documents/home/php-beast/tmpfile_file_handler.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/mrz/Documents/home/php-beast $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/mrz/Documents/home/php-beast/tmpfile_file_handler.c -o tmpfile_file_handler.lo  -MMD -MF tmpfile_file_handler.dep -MT tmpfile_file_handler.lo
-include pipe_file_handler.dep
pipe_file_handler.lo: /Users/mrz/Documents/home/php-beast/pipe_file_handler.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/mrz/Documents/home/php-beast $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/mrz/Documents/home/php-beast/pipe_file_handler.c -o pipe_file_handler.lo  -MMD -MF pipe_file_handler.dep -MT pipe_file_handler.lo
-include file_handler_switch.dep
file_handler_switch.lo: /Users/mrz/Documents/home/php-beast/file_handler_switch.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/mrz/Documents/home/php-beast $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/mrz/Documents/home/php-beast/file_handler_switch.c -o file_handler_switch.lo  -MMD -MF file_handler_switch.dep -MT file_handler_switch.lo
-include shm.dep
shm.lo: /Users/mrz/Documents/home/php-beast/shm.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/Users/mrz/Documents/home/php-beast $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /Users/mrz/Documents/home/php-beast/shm.c -o shm.lo  -MMD -MF shm.dep -MT shm.lo
$(phplibdir)/beast.la: ./beast.la
	$(LIBTOOL) --tag=CC --mode=install cp ./beast.la $(phplibdir)

./beast.la: $(shared_objects_beast) $(BEAST_SHARED_DEPENDENCIES)
	$(LIBTOOL) --tag=CC --mode=link $(CC) -shared $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_beast) $(BEAST_SHARED_LIBADD)

